### ISSUE TITLE
Will it work with full static export mode?

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/nuxt-generate-cluster#30] opened 2020-06-17 17:23 UTC
I am curious whether or not this will work with https://github.com/nuxt/nuxt.js/pull/6159 also described here https://www.notion.so/nuxt/Going-Full-Static-0633ab06d3d34d479947694d457a4817

I guess it would, but I am not sure since I guess the `-w 4` option is for `nuxt generate` only and not `nuxt export`?

**Comment by simplenotezy** [comment] 2020-06-30 09:40
Well, builds are working fine, but now sure how many workers it is using

**Comment by Spreizu** [comment] 2020-06-30 10:16
Workers seem to be working fine. However, static payload is not generated (static directory is missing inside _nuxt directory).

**Comment by pimlie** [comment] 2020-07-05 13:29
Unfortunately I have other priorities at the moment that prevents me from looking into supporting the new full static exports.

If someone wants to help with this, the issue is most likely that ngc doesnt use [Generator.generate](https://github.com/nuxt/nuxt.js/blob/dev/packages/generator/src/generator.js#L34), so indeed the static dirs arent created.

To properly support ngc then this [if statement](https://github.com/nuxt/nuxt.js/blob/dev/packages/generator/src/generator.js#L39) needs to be transformed to a method on the Generator class. When that Nuxt.js PR is merged we can fix ngc to use that method in [ngc's initiate call](https://github.com/nuxt-community/nuxt-generate-cluster/blob/master/lib/generate/master.js#L75).

But probably there are some more changes required, the above is just what I noticed from a first glance. Thanks.

**Comment by Spreizu** [comment] 2020-07-14 13:25
Created a pull request, that resolves this issue: #32

**Comment by Spreizu** [comment] 2020-08-12 08:07
Nuxt 2.14 resolved this issue.

**Closed as completed** 2020-12-02 12:20 UTC
